---
- name: Get Composer installer signature.
  uri:
    url: https://composer.github.io/installer.sig
    return_content: true
  register: composer_installer_signature

- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
    checksum: "sha384:{{ composer_installer_signature.content }}"

- name: Run Composer installer.
  command: >
    php composer-installer.php
    chdir=/tmp

- name: Move Composer into globally-accessible location
  command: >
    mv /tmp/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer